name: Submit a slack notification
on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      webhook_url:
        required: true
        type: string
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ inputs.message }}*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/${{ env.GITHUB_REPOSITORY }}|${{ env.GITHUB_REPOSITORY }}>\n*<https://github.com/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}|${{ env.GITHUB_SHA }}>*"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Triggered by: <https://github.com/${{ env.GITHUB_ACTOR }}|@${{ env.GITHUB_ACTOR }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ env.GITHUB_REF_NAME }}@<https://github.com/${{ env.GITHUB_REPOSITORY }}/commit/${{ env.GITHUB_SHA }}|${{ env.GITHUB_SHA }}>"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.webhook_url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
