name: Submit a slack notification
on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      message:
        required: true
        type: string
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      sha:
        required: true
        type: string
    secrets:
      webhook_url:
        required: true
jobs:
  notify:
    name: Send slack notification
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Build message
        run: |
          SHA="${{ inputs.sha }}"
          REF="${{ inputs.ref }}"
          BRANCH=${REF##*/}

          # Escape the message and title to be able to embed it in JSON
          cat << NOTIFICATION | head -c -1 > notification.txt
          ${{ inputs.title }}
          NOTIFICATION

          cat << TITLE | head -c -1 > title.txt

          *${{ inputs.title }}*
          TITLE

          # Format the message body
          echo "><https://github.com/${{ inputs.repository }}/tree/$BRANCH|$BRANCH> — <https://github.com/${{ inputs.repository }}|${{ inputs.repository }}>" >> message.txt
          echo "${{ inputs.message }}" | while read LINE; do
            echo ">*<https://github.com/${{ inputs.repository }}/actions/runs/$GITHUB_RUN_ID|$LINE>*" >> message.txt
          done

          cat << PAYLOAD > payload.json
          {
            "text": $(cat notification.txt | jq -R -s '.'),
            "blocks": [
              {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": $(cat title.txt | jq -R -s '.')
                  }
              },
              {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": $(cat message.txt | jq -R -s '.')
                  },
                  "accessory": {
                      "type": "button",
                      "url": "https://github.com/${{ inputs.repository }}/actions/runs/$GITHUB_RUN_ID",
                      "text": {
                          "type": "plain_text",
                          "text": "View progress"
                      }
                  }
              },
              {
                  "type": "divider"
              },
              {
                  "type": "context",
                  "elements": [
                      {
                          "type": "mrkdwn",
                          "text": "$BRANCH@<https://github.com/${{ inputs.repository }}/commit/$SHA|${SHA:0:8}>"
                      },
                      {
                          "type": "mrkdwn",
                          "text": "Triggered by: <https://github.com/$GITHUB_ACTOR|@$GITHUB_ACTOR>"
                      }
                  ]
              }
            ]
          }
          PAYLOAD

          echo "Submitting message with payload:"
          cat payload.json
      - name: Send message to slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload-file-path: ./payload.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.webhook_url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
