name: Submit a slack notification
on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      message:
        required: true
        type: string
    secrets:
      webhook_url:
        required: true
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Build message
        run: |
          # Escape the message and title to be able to embed it in JSON
          cat << NOTIFICATION | head -c -1 | jq -R -s '.' > notification.txt
          ${{ inputs.title }}
          NOTIFICATION

          cat << TITLE | head -c -1 | jq -R -s '.' > title.txt

          *${{ inputs.title }}*
          TITLE

          cat << MESSAGE | head -c -1 | jq -R -s '.' > message.txt
          ><https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_REF_NAME|$GITHUB_REF_NAME> — <https://github.com/$GITHUB_REPOSITORY|$GITHUB_REPOSITORY>\n>*<https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|${{ inputs.message }}>*
          MESSAGE

          cat << PAYLOAD > payload.json
          {
            "text": $(cat notification.txt),
            "blocks": [
              {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": $(cat title.txt)
                  }
              },
              {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": $(cat message.txt)
                  },
                  "accessory": {
                      "type": "button",
                      "url": "https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID",
                      "text": {
                          "type": "plain_text",
                          "text": "View progress"
                      }
                  }
              },
              {
                  "type": "divider"
              },
              {
                  "type": "context",
                  "elements": [
                      {
                          "type": "mrkdwn",
                          "text": "$GITHUB_REF_NAME@<https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA|${GITHUB_SHA:0:8}>"
                      },
                      {
                          "type": "mrkdwn",
                          "text": "Triggered by: <https://github.com/$GITHUB_ACTOR|@$GITHUB_ACTOR>"
                      }
                  ]
              }
            ]
          }
          PAYLOAD

          echo "Submitting message with payload:"
          cat payload.json
      - name: Send message to slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload-file-path: ./payload.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.webhook_url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
